"""Updating blacklist_tokens table

Revision ID: 6636d4123c5a
Revises: c0505b7a28d2
Create Date: 2024-03-07 21:08:12.266580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6636d4123c5a'
down_revision: Union[str, None] = 'c0505b7a28d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklisted_tokens', 'id',
               type_=sa.Integer(),
               postgresql_using='id::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklisted_tokens', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
