"""Adding column to record token in the blacklisted table

Revision ID: c0505b7a28d2
Revises: ac8ad8e32588
Create Date: 2024-03-07 20:34:52.528064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0505b7a28d2'
down_revision: Union[str, None] = 'ac8ad8e32588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column(
        'token', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
